// Generated by LiveScript 1.2.0
(function(){
  $(function(){
    var CACHED, GET, $in, $out;
    CACHED = {};
    GET = function(url, data, onSuccess, dataType){
      var ref$;
      if (data instanceof Function) {
        ref$ = [null, onSuccess, data], data = ref$[0], dataType = ref$[1], onSuccess = ref$[2];
      }
      if (CACHED[url]) {
        return onSuccess(CACHED[url]);
      }
      return $.get(url, data, function(it){
        return onSuccess(CACHED[url] = it);
      }, dataType || 'json').fail(function(){});
    };
    $in = $('#input');
    $out = $('#output');
    return GET("prox.json", function(Shape){
      var origin;
      origin = "http://127.0.0.1:8888/";
      window.id = 'tmuse';
      window.reset = function(){
        return $in.val('');
      };
      window.addEventListener("message", function(it){
        return window.input(it.data, false);
      });
      window.input = function(it){
        var i$, ref$, len$, label, results$ = [];
        $in.val(it);
        if (!Shape[it]) {
          return;
        }
        $out.empty();
        for (i$ = 0, len$ = (ref$ = Shape[it]).length; i$ < len$; ++i$) {
          label = ref$[i$];
          results$.push($out.append($('<li/>').append($('<a/>', {
            href: '#'
          }).text(label)).click(fn$)));
        }
        return results$;
        function fn$(){
          return window.output($(this).text());
        }
      };
      return window.output = function(it){
        if (window.muted) {
          return;
        }
        input(it);
        return window.top.postMessage(it, origin);
      };
    });
  });
}).call(this);
