// Generated by LiveScript 1.2.0
(function(){
  var frame, win;
  window.addEventListener('message', function(event){
    return console.log(event.data);
  });
  frame = document.getElementById('lhc');
  win = frame.contentWindow || frame.contentDocument;
  if (!win.document) {
    win = win.getParentNode();
  }
  win.postMessage($('#in').val(), "http://direct.moedict.tw/");
}).call(this);
