// Generated by LiveScript 1.2.0
(function(){
  var origin, buffer, myInput, myOutput, CharComp, CompChar, OrigChars, msgBeforeData, msgAfterData;
  Array.prototype.powerset = String.prototype.powerset = function(){
    var xs, x, p;
    if (this.length <= 1) {
      return this;
    }
    xs = Array.prototype.slice.call(this);
    x = Array.prototype.pop.call(xs);
    p = xs.powerset();
    return p.concat(p.map(function(it){
      return it.concat([x]);
    }));
  };
  origin = "http://127.0.0.1:8888/";
  buffer = [];
  myInput = "";
  myOutput = [];
  buffer = [];
  msgBeforeData = function(arg$){
    var data;
    data = arg$.data;
    return buffer.push(data);
  };
  msgAfterData = function(arg$){
    var data, comps, getComps, i$, ref$, len$, maybe, c;
    data = arg$.data;
    myInput = data;
    myOutput = [];
    comps = [];
    getComps = function(it){
      var out, i$, len$, char, comps;
      out = "";
      if (it.length <= 0) {
        return out;
      }
      for (i$ = 0, len$ = it.length; i$ < len$; ++i$) {
        char = it[i$];
        comps = CharComp[char];
        if (comps) {
          out += comps;
        }
      }
      return it + getComps(out);
    };
    comps = getComps(myInput);
    comps = Array.prototype.filter.call(comps, function(it){
      return !in$(it, myInput);
    });
    console.log(comps.powerset());
    for (i$ = 0, len$ = (ref$ = comps.powerset()).length; i$ < len$; ++i$) {
      maybe = ref$[i$];
      c = CompChar[maybe];
      if (c && in$(c, OrigChars)) {
        myOutput.push(c);
      }
    }
    return JSON.stringify(myOutput, void 8, 2);
  };
  window.id = 'lhc';
  window.reset = function(){
    return myInput = "";
  };
  window.input = function(it){
    return msgBeforeData({
      data: it
    });
  };
  window.addEventListener('message', msgBeforeData);
  window.output = function(it){
    if (window.muted) {
      return;
    }
    return window.top.postMessage(it, origin);
  };
  $.get('./data/char_comp_simple.json', function(d){
    CharComp = d;
    return $.get('./data/comp_char_simple.json', function(d){
      CompChar = d;
      return $.get('./data/orig-chars.json', function(d){
        var i$, ref$, len$, data;
        OrigChars = d;
        window.input = function(it){
          return msgAfterData({
            data: it
          });
        };
        window.removeEventListener('message', msgBeforeData);
        for (i$ = 0, len$ = (ref$ = buffer).length; i$ < len$; ++i$) {
          data = ref$[i$];
          msgAfterData({
            data: data
          });
        }
        return window.addEventListener('message', msgAfterData);
      });
    });
  });
  function in$(x, xs){
    var i = -1, l = xs.length >>> 0;
    while (++i < l) if (x === xs[i]) return true;
    return false;
  }
}).call(this);
