// Generated by LiveScript 1.6.0
(function(){
  $(function(){
    var origin, frames, i$, ref$, len$, x, prev, CACHED, GET;
    origin = "http://direct.moedict.tw/";
    frames = [];
    for (i$ = 0, len$ = (ref$ = $('iframe').get()).length; i$ < len$; ++i$) {
      x = ref$[i$];
      frames.push(x.contentWindow.window);
    }
    prev = '萌';
    window.id = 'hub';
    window.reset = function(){
      return input('');
    };
    window.post = (function(){
      function post(text, origin){
        var i$, ref$, len$, w, results$ = [];
        if (/^[-a-zA-Z\s]*$/.exec(text)) {
          return;
        }
        if ($(".project-" + origin + " > .tube-status").hasClass('close')) {
          return;
        }
        if (prev + "" === text + "") {
          return;
        }
        prev = text;
        if (typeof window.pushText == 'function') {
          window.pushText(text, origin);
        }
        for (i$ = 0, len$ = (ref$ = frames).length; i$ < len$; ++i$) {
          w = ref$[i$];
          if (w.id !== origin) {
            if (!$(".project-" + w.id + " > .tube-status").hasClass('close')) {
              results$.push((fn$.call(this, w)));
            }
          }
        }
        return results$;
        function fn$(w){
          return window.requestAnimationFrame(function(){
            return setTimeout(function(){
              return typeof w.input == 'function' ? w.input(prev, origin) : void 8;
            }, 1000);
          });
        }
      }
      return post;
    }());
    window.output = function(){};
    CACHED = {};
    return GET = function(url, data, onSuccess, dataType){
      var ref$;
      if (data instanceof Function) {
        ref$ = [null, onSuccess, data], data = ref$[0], dataType = ref$[1], onSuccess = ref$[2];
      }
      if (CACHED[url]) {
        return onSuccess(CACHED[url]);
      }
      return $.get(url, data, function(it){
        return onSuccess(CACHED[url] = it);
      }, dataType || 'json').fail(function(){});
    };
  });
}).call(this);
