// Generated by LiveScript 1.2.0
(function(){
  $(function(){
    var origin, i$, ref$, len$, x, CACHED, GET;
    origin = "http://127.0.0.1:8888/";
    this.frames = [];
    for (i$ = 0, len$ = (ref$ = $('iframe').get()).length; i$ < len$; ++i$) {
      x = ref$[i$];
      this.frames.push(x.contentWindow.window);
    }
    window.id = 'hub';
    window.reset = function(){
      return input('');
    };
    window.addEventListener("message", function(it){
      return window.input(it.data, false);
    });
    window.input = function(it){
      var i$, ref$, len$, w, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.frames).length; i$ < len$; ++i$) {
        w = ref$[i$];
        results$.push(w.postMessage(it, origin));
      }
      return results$;
    };
    window.output = function(){};
    CACHED = {};
    return GET = function(url, data, onSuccess, dataType){
      var ref$;
      if (data instanceof Function) {
        ref$ = [null, onSuccess, data], data = ref$[0], dataType = ref$[1], onSuccess = ref$[2];
      }
      if (CACHED[url]) {
        return onSuccess(CACHED[url]);
      }
      return $.get(url, data, function(it){
        return onSuccess(CACHED[url] = it);
      }, dataType || 'json').fail(function(){});
    };
  });
}).call(this);
